# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
jobs:
  - job: Test
    pool :
      vmImage: 'ubuntu-latest'
    steps:
      - template: .ci/templates/steps/initialize-environment.yml
      - template: .ci/templates/steps/test.yml
        parameters:
          codeCoverage: 'true'


  - job: Build
    pool :
      vmImage: 'ubuntu-latest'
    steps:
      - template: .ci/templates/steps/initialize-environment.yml
      - template: .ci/templates/steps/create-bundle.yml
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: dist/angular
          artifactName: '@uipath/angular'
        displayName: 'Publish @uipath/angular binaries'
        condition: succeeded()
